### ISSUE TITLE
Release this plugin as a gem

### ISSUE THREAD

**Issue by repeatedly** [vanilla/fluent-plugin-burrow#1]
https://rubygems.org/gems/fluent-plugin-burrow

Currently, burrow plugin is not available on rubygems.org.
Releasing plugin as a gem is useful for other users.

**Comment by repeatedly** [comment]
@kaecyra ping?

**Comment by kaecyra** [comment]
Will do.

**Comment by kaecyra** [comment]
Done. https://rubygems.org/gems/fluent-plugin-burrow

**Comment by repeatedly** [comment]
Awesome :+1: 
Thanks!
