### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tyranron** [vanilla/fluent-plugin-burrow#8]
First of all, thank you for nice plugin.
May I ask you to release new version of it to Gems repo?
Currently only [old versions are available](https://rubygems.org/gems/fluent-plugin-burrow/versions/) but #7 is quite valuable.
Also, it will be great to create Github releases which mirror versions of Gems repo and show current master branch state.

**Comment by cmachler** [comment]
@kaecyra let me know if there is anything I can do to help with this.

-Chris

**Comment by kaecyra** [comment]
This should now be done :) Thanks for kicking my butt.
